"""add search events

Revision ID: 7c762c443f40
Revises: 55197fbd8d1d
Create Date: 2026-08-06 08:54:01.969130
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "7c762c443f40"
down_revision: str | None = "55197fbd8d1d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_events",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("owner_id", sa.Uuid(), nullable=False),
        sa.Column("query", sa.String(length=512), nullable=False),
        sa.Column("normalized_query", sa.String(length=512), nullable=False),
        sa.Column("hit_count", sa.Integer(), nullable=False),
        sa.Column("took_ms", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("top_document_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_search_events_owner_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["top_document_id"],
            ["documents.id"],
            name=op.f("fk_search_events_top_document_id_documents"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_events")),
    )
    with op.batch_alter_table("search_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_search_events_normalized_query"), ["normalized_query"], unique=False
        )
        batch_op.create_index(
            "ix_search_events_owner_created", ["owner_id", "created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_search_events_owner_id"), ["owner_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("search_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_search_events_owner_id"))
        batch_op.drop_index("ix_search_events_owner_created")
        batch_op.drop_index(batch_op.f("ix_search_events_normalized_query"))

    op.drop_table("search_events")
    # ### end Alembic commands ###
